spring :
  datasource :
    url : jdbc:mysql://127.0.0.1:3306/tmall_springboot?useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    cache: false
server:
    port: 8086
